name: CI

on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["310", "311", "312", "313"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run tests
        run:  uv tool run --with=tox-uv tox r -e py${{ matrix.python-version }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    environment: release
    permissions:
      # IMPORTANT: This is required to publish to PyPI using Trusted Publishing.
      # See: https://docs.pypi.org/trusted-publishers/using-a-publisher/
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish --trusted-publishing always
